[project]
name = "client"
version = "0.1.0"
description = "Terminal chat client"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.10",
    "asciimatics>=1.15.0",
    "colorama>=0.4.6",
    "cryptography>=44.0.0",
    "pyinstaller>=6.11.1",
    "pyyaml>=6.0.2",
]
